export const tipsEnglish = [
    "Drink more water.",
    "Take breaks regularly.",
    "Stay positive and focused.",
    "Read a book for at least 30 minutes.",
    "Exercise for at least 30 minutes.",
    "Meditate for 10 minutes.",
    "Learn something new today.",
    "Stay organized and plan your day.",
    "Get enough sleep.",
    "Practice gratitude.",
    "Eat more fruits and vegetables.",
    "Avoid excessive sugar intake.",
    "Take a walk outside.",
    "Stretch your body.",
    "Set realistic goals.",
    "Take deep breaths.",
    "Smile more often.",
    "Listen to your favorite music.",
    "Keep a journal.",
    "Spend time with loved ones.",
    "Limit screen time.",
    "Try a new hobby.",
    "Stay hydrated.",
    "Practice good posture.",
    "Get some fresh air.",
    "Laugh often.",
    "Plan your meals ahead.",
    "Stay curious.",
    "Disconnect from social media occasionally.",
    "Volunteer your time.",
    "Declutter your space.",
    "Take time to relax.",
    "Practice self-care.",
    "Set boundaries.",
    "Stay patient.",
    "Believe in yourself.",
    "Learn to say no.",
    "Be kind to yourself.",
    "Focus on the present.",
    "Reduce caffeine intake.",
    "Spend time in nature.",
    "Take care of your mental health.",
    "Celebrate small wins.",
    "Keep learning.",
    "Practice mindfulness.",
    "Stay connected with friends.",
    "Listen to podcasts.",
    "Watch educational videos.",
    "Take care of your skin.",
    "Cook a new recipe.",
    "Practice yoga.",
    "Stay humble.",
    "Save money regularly.",
    "Avoid negative people.",
    "Keep your living space clean.",
    "Stay flexible in your thinking.",
    "Write down your thoughts.",
    "Make time for fun.",
    "Be proactive.",
    "Eat mindfully.",
    "Take regular breaks from work.",
    "Be grateful for what you have.",
    "Set a sleep schedule.",
    "Listen actively.",
    "Take care of your teeth.",
    "Avoid comparing yourself to others.",
    "Take on new challenges.",
    "Stay motivated.",
    "Plan a trip.",
    "Spend time with pets.",
    "Keep a positive attitude.",
    "Stay calm under pressure.",
    "Prioritize your tasks.",
    "Be open to new experiences.",
    "Stay true to your values.",
    "Communicate clearly.",
    "Stay focused on your goals.",
    "Keep a balance in life.",
    "Maintain healthy relationships.",
    "Challenge yourself.",
    "Seek out feedback.",
    "Practice empathy.",
    "Be a good listener.",
    "Stay disciplined.",
    "Stay organized.",
    "Be mindful of your thoughts.",
    "Stay active.",
    "Take care of your body.",
    "Practice gratitude daily.",
    "Stay creative.",
    "Invest in yourself.",
    "Stay informed.",
    "Help others.",
    "Be accountable.",
    "Practice forgiveness.",
    "Be consistent.",
    "Stay persistent.",
    "Embrace change.",
    "Take responsibility.",
    "Learn from mistakes.",
    "Stay focused on solutions.",
    "Maintain a positive environment.",
    "Stay enthusiastic.",
    "Encourage others.",
    "Stay respectful.",
    "Seek out new knowledge.",
    "Stay adaptable.",
    "Stay grounded.",
    "Take calculated risks.",
    "Focus on your strengths.",
    "Develop new skills.",
    "Stay committed.",
    "Stay aware of your surroundings.",
    "Practice patience.",
    "Keep a growth mindset.",
    "Stay humble.",
    "Reflect on your day.",
    "Take care of your mental health.",
    "Stay true to yourself.",
    "Avoid procrastination.",
    "Stay diligent.",
    "Stay hopeful.",
    "Keep an open mind.",
    "Stay resourceful.",
    "Stay honest.",
    "Stay positive.",
    "Stay kind.",
    "Stay grateful.",
    "Stay curious.",
    "Stay helpful.",
    "Stay considerate.",
    "Stay respectful.",
    "Stay understanding.",
    "Stay compassionate.",
    "Stay focused.",
    "Stay motivated.",
    "Stay determined.",
    "Stay enthusiastic.",
    "Stay committed.",
    "Stay consistent.",
    "Stay patient.",
    "Stay proactive.",
    "Stay adaptable.",
    "Stay responsible.",
    "Stay humble.",
    "Stay diligent.",
    "Stay hopeful.",
    "Stay kind."
  ];
  
  export const tipsUkrainian = [
    "Пийте більше води.",
    "Робіть перерви регулярно.",
    "Залишайтеся позитивними та зосередженими.",
    "Читайте книгу щонайменше 30 хвилин.",
    "Займайтеся фізичними вправами щонайменше 30 хвилин.",
    "Медитуйте 10 хвилин.",
    "Вчіться чомусь новому сьогодні.",
    "Будьте організованими та плануйте свій день.",
    "Достатньо спіть.",
    "Практикуйте вдячність.",
    "Їжте більше фруктів та овочів.",
    "Уникайте надмірного вживання цукру.",
    "Прогуляйтеся на вулиці.",
    "Розтягуйте своє тіло.",
    "Ставте реалістичні цілі.",
    "Глибоко дихайте.",
    "Частіше посміхайтеся.",
    "Слухайте свою улюблену музику.",
    "Ведіть щоденник.",
    "Проводьте час з близькими.",
    "Обмежуйте час перед екраном.",
    "Спробуйте нове хобі.",
    "Підтримуйте водний баланс.",
    "Практикуйте хорошу поставу.",
    "Отримуйте свіже повітря.",
    "Частіше смійтеся.",
    "Плануйте свої страви заздалегідь.",
    "Будьте цікавими.",
    "Іноді відключайтеся від соціальних мереж.",
    "Добровільно допомагайте.",
    "Позбавляйтеся непотрібних речей.",
    "Знайдіть час для відпочинку.",
    "Практикуйте самодогляд.",
    "Встановлюйте межі.",
    "Будьте терплячими.",
    "Вірте в себе.",
    "Навчіться казати 'ні'.",
    "Будьте добрими до себе.",
    "Зосередьтеся на теперішньому.",
    "Зменшуйте споживання кофеїну.",
    "Проводьте час на природі.",
    "Дбайте про своє психічне здоров'я.",
    "Святкуйте маленькі перемоги.",
    "Продовжуйте вчитися.",
    "Практикуйте уважність.",
    "Підтримуйте зв'язок з друзями.",
    "Слухайте подкасти.",
    "Дивіться освітні відео.",
    "Дбайте про свою шкіру.",
    "Готуйте нові рецепти.",
    "Практикуйте йогу.",
    "Будьте скромними.",
    "Регулярно заощаджуйте гроші.",
    "Уникайте негативних людей.",
    "Тримайте свій простір чистим.",
    "Будьте гнучкими у своєму мисленні.",
    "Записуйте свої думки.",
    "Знаходьте час для розваг.",
    "Будьте проактивними.",
    "Їжте усвідомлено.",
    "Робіть регулярні перерви в роботі.",
    "Будьте вдячні за те, що маєте.",
    "Встановлюйте режим сну.",
    "Слухайте уважно.",
    "Дбайте про свої зуби.",
    "Уникайте порівнювань себе з іншими.",
    "Беруться за нові виклики.",
    "Залишайтеся мотивованими.",
    "Плануйте подорожі.",
    "Проводьте час з домашніми улюбленцями.",
    "Тримайте позитивне ставлення.",
    "Залишайтеся спокійними під тиском.",
    "Пріоритизуйте свої завдання.",
    "Будьте відкритими до нових вражень.",
    "Залишайтеся вірними своїм цінностям.",
    "Спілкуйтеся чітко.",
    "Зосередьтеся на своїх цілях.",
    "Зберігайте баланс у житті.",
    "Підтримуйте здорові відносини.",
    "Кидайте собі виклики.",
    "Шукайте зворотній зв'язок.",
    "Практикуйте емпатію.",
    "Будьте гарним слухачем.",
    "Залишайтеся дисциплінованими.",
    "Будьте організованими.",
    "Уважно стежте за своїми думками.",
    "Залишайтеся активними.",
    "Дбайте про своє тіло.",
    "Практикуйте щоденну вдячність.",
    "Будьте творчими.",
    "Інвестуйте в себе.",
    "Залишайтеся поінформованими.",
    "Допомагайте іншим.",
    "Будьте відповідальними.",
    "Практикуйте прощення.",
    "Будьте послідовними.",
    "Залишайтеся наполегливими.",
    "Приймайте зміни.",
    "Беріть відповідальність.",
    "Навчайтеся на помилках.",
    "Зосередьтеся на рішеннях.",
    "Підтримуйте позитивне середовище.",
    "Будьте ентузіастами.",
    "Заохочуйте інших.",
    "Будьте поважними.",
    "Шукайте нові знання.",
    "Будьте адаптивними.",
    "Залишайтеся приземленими.",
    "Розраховуйте ризики.",
    "Зосередьтеся на своїх сильних сторонах.",
    "Розвивайте нові навички.",
    "Залишайтеся вірними.",
    "Будьте обережними.",
    "Практикуйте терпіння.",
    "Зберігайте зростаючий менталітет.",
    "Будьте скромними.",
    "Рефлексуйте над своїм днем.",
    "Дбайте про своє психічне здоров'я.",
    "Залишайтеся вірними собі.",
    "Уникайте прокрастинації.",
    "Будьте старанними.",
    "Залишайтеся надійними.",
    "Зберігайте відкритий розум.",
    "Будьте винахідливими.",
    "Будьте чесними.",
    "Будьте позитивними.",
    "Будьте добрими.",
    "Будьте вдячними.",
    "Будьте цікавими.",
    "Будьте корисними.",
    "Будьте уважними.",
    "Будьте поважними.",
    "Будьте розуміючими.",
    "Будьте співчутливими.",
    "Будьте зосередженими.",
    "Будьте мотивованими.",
    "Будьте рішучими.",
    "Будьте ентузіастами.",
    "Будьте вірними.",
    "Будьте послідовними.",
    "Будьте терплячими.",
    "Будьте проактивними.",
    "Будьте адаптивними.",
    "Будьте відповідальними.",
    "Будьте скромними.",
    "Будьте старанними.",
    "Залишайтеся надійними.",
    "Будьте добрими."
  ];
  